[package]
name = "parselens-wasm"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
parselens-core = { path = "../parselens-core" }
parselens-repr = { path = "../parselens-repr" }
serde_json.workspace = true
wasm-bindgen.workspace = true
