[package]
name = "parselens-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "parselens"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
parselens-core = { path = "../parselens-core" }
parselens-repr = { path = "../parselens-repr" }
serde_json.workspace = true
